require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/grain_jars", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # GrainJar. As you add validations to GrainJar, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      GrainJar.create! valid_attributes
      get grain_jars_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grain_jar = GrainJar.create! valid_attributes
      get grain_jar_url(grain_jar)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grain_jar_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      grain_jar = GrainJar.create! valid_attributes
      get edit_grain_jar_url(grain_jar)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new GrainJar" do
        expect {
          post grain_jars_url, params: { grain_jar: valid_attributes }
        }.to change(GrainJar, :count).by(1)
      end

      it "redirects to the created grain_jar" do
        post grain_jars_url, params: { grain_jar: valid_attributes }
        expect(response).to redirect_to(grain_jar_url(GrainJar.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new GrainJar" do
        expect {
          post grain_jars_url, params: { grain_jar: invalid_attributes }
        }.to change(GrainJar, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post grain_jars_url, params: { grain_jar: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grain_jar" do
        grain_jar = GrainJar.create! valid_attributes
        patch grain_jar_url(grain_jar), params: { grain_jar: new_attributes }
        grain_jar.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the grain_jar" do
        grain_jar = GrainJar.create! valid_attributes
        patch grain_jar_url(grain_jar), params: { grain_jar: new_attributes }
        grain_jar.reload
        expect(response).to redirect_to(grain_jar_url(grain_jar))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        grain_jar = GrainJar.create! valid_attributes
        patch grain_jar_url(grain_jar), params: { grain_jar: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grain_jar" do
      grain_jar = GrainJar.create! valid_attributes
      expect {
        delete grain_jar_url(grain_jar)
      }.to change(GrainJar, :count).by(-1)
    end

    it "redirects to the grain_jars list" do
      grain_jar = GrainJar.create! valid_attributes
      delete grain_jar_url(grain_jar)
      expect(response).to redirect_to(grain_jars_url)
    end
  end
end
