default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_docker: &default_docker
  <<: *default
  database: SHROOM_SAFE_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: <%= ENV["DB_PORT"] %>

development:
  <<: *default_docker
  database: SHROOM_SAFE_development

test:
  <<: *default_docker
  database: SHROOM_SAFE_test

production:
  <<: *default
  database: SHROOM_SAFE_production
  username: SHROOM_SAFE
  password: <%= ENV["SHROOM_SAFE_DATABASE_PASSWORD"] %>
